# -*- coding: utf-8 -*-
"""sql_setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASEtadgVej5b7yojYp0O554RYlVD3RK0
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql
from google.colab import userdata
# %pip install pymysql
# %sql mariadb+pymysql://admin:{userdata.get('password')}@database-ads-jd2016.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
# %config SqlMagic.style = '_DEPRECATED_DEFAULT'
# %sql USE ads_2024